const invertory = [
  {
    id: 1,
    name: "Notebook",
    category: "Stationery",
    quantity: 25,
    price: 50,
  },
  {
    id: 2,
    name: "Pen",
    category: "Stationery",
    quantity: 8,
    price: 10,
  },
  {
    id: 3,
    name: "Laptop",
    category: "Electronics",
    quantity: 15,
    price: 50000,
  },
  {
    id: 4,
    name: "Mouse",
    category: "Electronics",
    quantity: 5,
    price: 800,
  },
  {
    id: 5,
    name: "Coffee Mug",
    category: "Kitchenware",
    quantity: 12,
    price: 200,
  },
  {
    id: 6,
    name: "Headphones",
    category: "Electronics",
    quantity: 7,
    price: 2000,
  },
  {
    id: 7,
    name: "Chair",
    category: "Furniture",
    quantity: 20,
    price: 1500,
  },
  {
    id: 8,
    name: "Desk",
    category: "Furniture",
    quantity: 10,
    price: 3000,
  },
  {
    id: 9,
    name: "Water Bottle",
    category: "Kitchenware",
    quantity: 18,
    price: 300,
  },
  {
    id: 10,
    name: "Backpack",
    category: "Accessories",
    quantity: 9,
    price: 1200,
  },
  {
    id: 11,
    name: "Socks",
    category: "Clothing",
    quantity: 30,
    price: 100,
  },
  {
    id: 12,
    name: "T-shirt",
    category: "Clothing",
    quantity: 13,
    price: 500,
  },
  {
    id: 13,
    name: "Mobile Phone",
    category: "Electronics",
    quantity: 6,
    price: 25000,
  },
  {
    id: 14,
    name: "Table Lamp",
    category: "Lighting",
    quantity: 16,
    price: 800,
  },
  {
    id: 15,
    name: "Electric Kettle",
    category: "Kitchenware",
    quantity: 4,
    price: 1500,
  },
  {
    id: 16,
    name: "Bluetooth Speaker",
    category: "Electronics",
    quantity: 14,
    price: 3500,
  },
  {
    id: 17,
    name: "Running Shoes",
    category: "Footwear",
    quantity: 11,
    price: 3000,
  },
  {
    id: 18,
    name: "Gym Bag",
    category: "Accessories",
    quantity: 8,
    price: 1200,
  },
  {
    id: 19,
    name: "Curtains",
    category: "Home Decor",
    quantity: 5,
    price: 2000,
  },
  {
    id: 20,
    name: "Wall Clock",
    category: "Home Decor",
    quantity: 22,
    price: 1500,
  },
];

export {invertory};